services:
  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: productvault-prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=7d
    ports:
      - "9090:9090"
    volumes:
      - ./Monitoring/Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:12.1.1
    container_name: productvault-grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./Monitoring/Grafana/provisioning:/etc/grafana/provisioning:ro
      - ./Monitoring/Grafana/dashboards:/var/lib/grafana/dashboards:ro

volumes:
  prometheus-data:
  grafana-data:
