apiVersion: 1

datasources:
  - name: ProductVault Prometheus
    uid: productvault-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
